import { useState } from 'react';
import { suggestedId, upsertDraft, localizeDraft, registerSymbols, type StudioDraft, type StudioChoices, type Element, type Recipe, type SetDefinition, type CollectionDefinition, type AnomalyDefinition, type UnlockDefinition, type Requirement } from '../../application/packs/authoring';
import { ChoicePicker, MemberPicker, RequirementEditor } from './AuthorControls';
import { ElementArt } from '../components/ElementArt';
type FormProps={draft:StudioDraft;choices:StudioChoices;commit:(draft:StudioDraft|(()=>StudioDraft))=>void};
const split=(value:string)=>value.split(',').map(s=>s.trim()).filter(Boolean);
function IdField({value,change,editing,suggestion}:{value:string;change:(s:string)=>void;editing:boolean;suggestion:string}){return <label>Identificatore<input value={value} readOnly={editing} onChange={e=>change(e.target.value)} placeholder={suggestion} maxLength={80}/><small>{editing?'Stabile: cambiarlo richiede una migrazione.':'Lascia vuoto per usare il suggerimento. Deve essere unico.'}</small></label>;}
export function ElementForm({draft,choices,commit,current,image}:{ } & FormProps & {current?:Element;image:(id:string,key:string,file:File)=>void}){
  const [name,setName]=useState(current?draft.patch.locales?.it[current.nameKey]??current.id:''),[description,setDescription]=useState(current?draft.patch.locales?.it[current.descriptionKey]??'':''),[id,setIdentifier]=useState(current?.id??'');
  const [setId,setSet]=useState(current?.setId??'origins'),[rarity,setRarity]=useState<Element['rarity']>(current?.rarity??'common'),[completion,setCompletion]=useState<Element['completion']>(current?.completion??'bonus'),[visibility,setVisibility]=useState<Element['visibility']>(current?.visibility??'announced'),[tags,setTags]=useState(current?.tags.join(', ')??'');
  const identity=id||`${draft.manifest.namespace}_${suggestedId(name)}`, key=current?.artKey??`${draft.manifest.namespace}.${identity}`;
  const save=()=>commit(()=>{const element:Element={...current,id:identity,nameKey:current?.nameKey??`${draft.manifest.namespace}.elements.${identity}.name`,descriptionKey:current?.descriptionKey??`${draft.manifest.namespace}.elements.${identity}.description`,artKey:key,setId,rarity,completion,visibility,tags:split(tags)};
    return registerSymbols(localizeDraft(upsertDraft(draft,'elements',element,current?.id),element,name,description),'tags',element.tags);});
  return <form onSubmit={e=>{e.preventDefault();save();}}><h4>{current?'Modifica elemento':'Nuovo elemento'}</h4><div className="studio-grid"><div><label>Nome elemento<input required value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>Descrizione elemento<textarea required value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000}/></label><IdField value={id} change={setIdentifier} editing={!!current} suggestion={identity}/><ChoicePicker label="Set dell’elemento" value={setId} change={setSet} choices={choices.sets}/></div>
    <div><div className="studio-art"><ElementArt artKey={key}/><p>Studio dell’elemento · fallback simbolico se manca il raster.</p></div><label>Rarità<select value={rarity} onChange={e=>setRarity(e.target.value as Element['rarity'])}>{['common','uncommon','rare','extraordinary','secret'].map(s=><option key={s}>{s}</option>)}</select></label><label>Completamento<select value={completion} onChange={e=>setCompletion(e.target.value as Element['completion'])}><option value="required">Richiesto nel Set</option><option value="bonus">Bonus</option><option value="secret">Segreto</option></select></label><label>Visibilità elemento<select value={visibility} onChange={e=>setVisibility(e.target.value as Element['visibility'])}><option value="announced">Annunciato</option><option value="glimpsed">Intravisto</option><option value="hidden">Nascosto</option><option value="secret">Segreto</option></select></label><label>Tag · separati da virgole<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="es. aquatic, plant"/></label></div></div>
    <button type="submit" className="secondary warm" disabled={!name||!description||!setId}>{current?'Salva elemento':'Aggiungi elemento'}</button>
    {current&&<label>Immagine dell’elemento · PNG/WebP<input type="file" accept="image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)image(current.id,key,file);}}/></label>}
    {!current&&<p>Aggiungi l’elemento alla bozza, poi apri Modifica per assegnare l’immagine. Non diventa uno starter.</p>}</form>;
}
export function RecipeForm({draft,choices,commit,current,collisions}:{ } & FormProps & {current?:Recipe;collisions:(a:string,b:string,except?:string)=>void}){
  const [id,setId]=useState(current?.id??''),[a,setA]=useState(current?.inputs[0]??''),[b,setB]=useState(current?.inputs[1]??''),[result,setResult]=useState(current?.resultElementId??''),[discovery,setDiscovery]=useState<Recipe['discovery']>(current?.discovery??'normal');
  const [requirements,setRequirements]=useState<Requirement[]>(current?.requirements??[]),[gate,setGate]=useState<NonNullable<Recipe['gateBehavior']>>(current?.gateBehavior??'normal'),[fallback,setFallback]=useState<NonNullable<Recipe['gateFallback']>>(current?.gateFallback??'dormant'),[priority,setPriority]=useState(String(current?.priority??0));
  const identity=id||`${draft.manifest.namespace}_${a}_${b}_to_${result}`;
  return <form onSubmit={e=>{e.preventDefault();commit(()=>upsertDraft(draft,'recipes',{id:identity,inputs:[a,b],resultElementId:result,kind:'explicit',discovery,requirements,gateBehavior:gate,...gate==='unlock_trigger'?{gateFallback:fallback}:{},priority:Number(priority)} satisfies Recipe,current?.id));}}><h4>{current?'Modifica ricetta':'Nuova ricetta'}</h4>
    <div className="studio-grid"><ChoicePicker label="Ingrediente A" value={a} change={v=>{setA(v);collisions(v,b,current?.id);}} choices={choices.elements}/><ChoicePicker label="Ingrediente B" value={b} change={v=>{setB(v);collisions(a,v,current?.id);}} choices={choices.elements}/></div>
    <p>A+B e B+A sono la stessa coppia. A+A è valido soltanto con questa ricetta esplicita.</p><ChoicePicker label="Risultato della ricetta" value={result} change={setResult} choices={choices.elements}/><IdField value={id} change={setId} editing={!!current} suggestion={identity}/>
    <label>Tipo di scoperta<select value={discovery} onChange={e=>setDiscovery(e.target.value as Recipe['discovery'])}><option value="normal">Normale</option><option value="alternate">Alternativa</option><option value="secret">Segreta</option></select></label>
    <RequirementEditor value={requirements} change={setRequirements} {...choices}/><details><summary>Gate e priorità · avanzate</summary><label>Comportamento del gate<select value={gate} onChange={e=>setGate(e.target.value as NonNullable<Recipe['gateBehavior']>)}>{['normal','dormant','anomaly','unlock_trigger'].map(g=><option key={g}>{g}</option>)}</select></label>{gate==='unlock_trigger'&&<label>Fallback del gate<select value={fallback} onChange={e=>setFallback(e.target.value as NonNullable<Recipe['gateFallback']>)}><option value="dormant">Dormant</option><option value="anomaly">Anomalia</option></select></label>}<label>Priorità della ricetta<input type="number" value={priority} onChange={e=>setPriority(e.target.value)} /></label><p>Un’anomalia deve essere anche definita nel modulo Anomalie. La priorità non consente di sostituire coppie canoniche.</p></details>
    <button type="submit" disabled={!a||!b||!result}>{current?'Salva ricetta':'Aggiungi ricetta'}</button></form>;
}
export function SetForm({draft,choices,commit,current,image}:{ } & FormProps & {current?:SetDefinition;image:(id:string,file:File)=>void}){
  const [id,setId]=useState(current?.id??''),[name,setName]=useState(current?draft.patch.locales?.it[current.nameKey]??current.id:''),[description,setDescription]=useState(current?draft.patch.locales?.it[current.descriptionKey]??'':''),[era,setEra]=useState(current?.eraId??'origins'),[visibility,setVisibility]=useState<SetDefinition['visibility']>(current?.visibility??'discovery');
  const identity=id||`${draft.manifest.namespace}_${suggestedId(name)}`;
  return <form onSubmit={e=>{e.preventDefault();const item:SetDefinition={...current,id:identity,nameKey:current?.nameKey??`${draft.manifest.namespace}.sets.${identity}.name`,descriptionKey:current?.descriptionKey??`${draft.manifest.namespace}.sets.${identity}.description`,eraId:era,visibility,completionMode:'required_elements',accentToken:current?.accentToken??'--accent-origins',iconKey:current?.iconKey??`${draft.manifest.namespace}.${identity}`,sortOrder:current?.sortOrder??choices.nextSetOrder};commit(()=>localizeDraft(upsertDraft(draft,'sets',item,current?.id),item,name,description));}}><h4>{current?'Modifica Set':'Nuovo Set'}</h4>
    <label>Nome Set<input required value={name} onChange={e=>setName(e.target.value)} /></label><label>Descrizione Set<textarea required value={description} onChange={e=>setDescription(e.target.value)} /></label><IdField value={id} change={setId} editing={!!current} suggestion={identity}/><ChoicePicker label="Era del Set" value={era} change={setEra} choices={choices.eras}/><label>Visibilità Set<select value={visibility} onChange={e=>setVisibility(e.target.value as SetDefinition['visibility'])}>{['announced','discovery','hidden','secret'].map(s=><option key={s}>{s}</option>)}</select></label><p>Aggiungi almeno un membro richiesto e una regola di reveal nel modulo Unlock. Il validator controllerà la raggiungibilità.</p><button type="submit" disabled={!name||!description||!era}>{current?'Salva Set':'Aggiungi Set'}</button>{current&&<><div className="studio-art"><ElementArt artKey={current.iconKey}/></div><label>Immagine Set · PNG/WebP<input type="file" accept="image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)image(current.id,file);}}/></label></>}</form>;
}
export function CollectionForm({draft,choices,commit,current}:{ } & FormProps & {current?:CollectionDefinition}){
  const existingReveal=draft.patch.visibility?.collectionReveals.find(rule=>rule.collectionId===current?.id);
  const [id,setId]=useState(current?.id??''),[name,setName]=useState(current?draft.patch.locales?.it[current.nameKey]??current.id:''),[description,setDescription]=useState(current?draft.patch.locales?.it[current.descriptionKey]??'':''),[visibility,setVisibility]=useState<CollectionDefinition['visibility']>(current?.visibility??'visible'),[members,setMembers]=useState(current?.memberElementIds??[]),[reveal,setReveal]=useState('');
  const identity=id||`${draft.manifest.namespace}_${suggestedId(name)}`;
  return <form onSubmit={e=>{e.preventDefault();commit(()=>{const item:CollectionDefinition={...current,id:identity,nameKey:current?.nameKey??`${draft.manifest.namespace}.collections.${identity}.name`,descriptionKey:current?.descriptionKey??`${draft.manifest.namespace}.collections.${identity}.description`,visibility,memberElementIds:members};const next=localizeDraft(upsertDraft(draft,'collections',item,current?.id),item,name,description);
    if(reveal||(!existingReveal&&visibility==='visible')){next.patch.visibility??={initialRevealedSetIds:[],setAnnouncements:[],collectionReveals:[]};next.patch.visibility.collectionReveals=next.patch.visibility.collectionReveals.filter(v=>v.collectionId!==identity);next.patch.visibility.collectionReveals.push({collectionId:identity,paths:reveal?[[{type:'element_discovered',elementId:reveal}]]:[[]]});}return next;});}}><h4>{current?'Modifica Collezione':'Nuova Collezione'}</h4>
    <label>Nome Collezione<input required value={name} onChange={e=>setName(e.target.value)} /></label><label>Descrizione Collezione<textarea required value={description} onChange={e=>setDescription(e.target.value)} /></label><IdField value={id} change={setId} editing={!!current} suggestion={identity}/><label>Visibilità Collezione<select value={visibility} onChange={e=>setVisibility(e.target.value as CollectionDefinition['visibility'])}><option value="visible">Visibile</option><option value="hidden">Nascosta</option><option value="secret">Segreta</option></select></label><MemberPicker label="Membri della Collezione" selected={members} change={setMembers} choices={choices.elements}/>{visibility!=='visible'&&<ChoicePicker label="Rivela dopo questa scoperta" value={reveal} change={setReveal} choices={choices.elements} optional/>}
    {visibility==='visible'&&<><ChoicePicker label="Rivela dopo questa scoperta" value={reveal} change={setReveal} choices={choices.elements} optional/><p>Nessuno: disponibile dal primo ingresso alle Collezioni. Una scoperta selezionata crea un prerequisito esplicito. Le regole di reveal importate restano in uso se non scegli un nuovo prerequisito.</p></>}
    {current?.chapters?.length&&<p>{current.chapters.length} capitoli importati conservati. Questa versione modifica membri e testi della Collezione; l’editor dedicato dei capitoli è un seguito.</p>}
    <button type="submit" disabled={!name||!description||!members.length||(visibility!=='visible'&&!reveal&&!existingReveal)}>{current?'Salva Collezione':'Aggiungi Collezione'}</button></form>;
}
export function AnomalyForm({draft,choices,commit,current}:{ } & FormProps & {current?:AnomalyDefinition}){
  const [id,setId]=useState(current?.id??''),[a,setA]=useState(current?.inputs[0]??''),[b,setB]=useState(current?.inputs[1]??''),[message,setMessage]=useState(current?draft.patch.locales?.it[current.messageKey]??'':''),[category,setCategory]=useState<AnomalyDefinition['category']>(current?.category??'unknown'),[resolution,setResolution]=useState(current?.resolutionRecipeId??''),[requirements,setRequirements]=useState(current?.requirements??[]);
  const identity=id||`${draft.manifest.namespace}_anomaly_${a}_${b}`;
  return <form onSubmit={e=>{e.preventDefault();commit(()=>{const messageKey=current?.messageKey??`${draft.manifest.namespace}.anomalies.${identity}.message`;const next=upsertDraft(draft,'anomalies',{id:identity,inputs:[a,b],messageKey,visibility:'archive',category,requirements,...resolution?{resolutionRecipeId:resolution}:{}} satisfies AnomalyDefinition,current?.id);next.patch.locales??={it:{}};next.patch.locales.it[messageKey]=message;return next;});}}><h4>{current?'Modifica anomalia':'Nuova anomalia'}</h4><div className="studio-grid"><ChoicePicker label="Primo input dell’anomalia" value={a} change={setA} choices={choices.elements}/><ChoicePicker label="Secondo input dell’anomalia" value={b} change={setB} choices={choices.elements}/></div><label>Messaggio dell’anomalia<textarea required value={message} onChange={e=>setMessage(e.target.value)} /></label><IdField value={id} change={setId} editing={!!current} suggestion={identity}/><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value as AnomalyDefinition['category'])}>{['unknown','mythic','spiritual','dimensional'].map(c=><option key={c}>{c}</option>)}</select></label><ChoicePicker label="Ricetta di risoluzione" value={resolution} change={setResolution} choices={choices.recipes} optional/><RequirementEditor value={requirements} change={setRequirements} {...choices}/><button type="submit" disabled={!a||!b||!message}>{current?'Salva anomalia':'Aggiungi anomalia'}</button></form>;
}
export function UnlockForm({draft,choices,commit,current}:{ } & FormProps & {current?:UnlockDefinition}){
  const [id,setId]=useState(current?.id??''),[kind,setKind]=useState<UnlockDefinition['target']['type']>(current?.target.type??'set'),[target,setTarget]=useState(current?current.target.type==='set'?current.target.setId:current.target.type==='era'?current.target.eraId:current.target.featureId:''),[requirements,setRequirements]=useState(current?.requirements??[]),[mode,setMode]=useState<UnlockDefinition['revealMode']>(current?.revealMode??'normal');
  const identity=id||`${draft.manifest.namespace}_unlock_${target}`;
  return <form onSubmit={e=>{e.preventDefault();const output:UnlockDefinition['target']=kind==='set'?{type:kind,setId:target}:kind==='era'?{type:kind,eraId:target}:{type:kind,featureId:target};commit(()=>upsertDraft(draft,'unlocks',{id:identity,target:output,requirements,revealMode:mode} satisfies UnlockDefinition,current?.id));}}><h4>{current?'Modifica Unlock':'Nuovo Unlock'}</h4><label>Tipo di sblocco<select value={kind} onChange={e=>{setKind(e.target.value as UnlockDefinition['target']['type']);setTarget('');}}><option value="set">Set</option><option value="era">Era</option><option value="feature">Funzione registrata</option></select></label><ChoicePicker label="Destinazione dello sblocco" value={target} change={setTarget} choices={kind==='set'?choices.sets:kind==='era'?choices.eras:choices.features}/><IdField value={id} change={setId} editing={!!current} suggestion={identity}/><RequirementEditor value={requirements} change={setRequirements} {...choices}/><label>Presentazione reveal<select value={mode} onChange={e=>setMode(e.target.value as UnlockDefinition['revealMode'])}><option value="silent">Silenziosa</option><option value="normal">Normale</option><option value="major">Maggiore</option></select></label><button type="submit" disabled={!target}>{current?'Salva Unlock':'Aggiungi Unlock'}</button><p>I target shipped non vengono sovrascritti. Le funzioni registrate non aggiungono codice al gioco.</p></form>;
}
