import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdirSync, readFileSync } from 'node:fs';
import { readPack } from '../../src/content/packs/archive';
async function open(page:Page){await page.goto('/settings');await page.getByLabel('Attiva modalità autore locale').check();await page.getByRole('button',{name:'Apri Studio contenuti',exact:true}).click();await expect(page.getByLabel('Titolo del pacchetto')).toBeVisible();}
async function tab(page:Page,name:string){await page.getByRole('navigation',{name:'Sezioni dello Studio'}).getByRole('button',{name,exact:true}).click();}
async function shot(page:Page,name:string){mkdirSync('docs/screenshots/content-1b',{recursive:true});await page.screenshot({path:`docs/screenshots/content-1b/${name}.png`,animations:'disabled'});}
async function audit(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);}
test('visual authoring creates a localized element/image/alternative-ready recipe/Collection, exports and installs with no automatic discoveries',async({page})=>{
  await open(page);await page.locator('.content-studio header').scrollIntoViewIfNeeded();await shot(page,'1440-studio-overview');
  await page.getByLabel('Titolo del pacchetto').fill('Prova autore · non canonica');await page.getByLabel('Identificatore del pacchetto',{exact:true}).fill('studio_browser');await page.getByLabel('Namespace del pacchetto').fill('studio_browser');
  await tab(page,'Elementi');await page.getByLabel('Nome elemento',{exact:true}).fill('Gemma di prova');await page.getByLabel('Descrizione elemento').fill('Elemento sintetico creato con il modulo visuale.');await page.getByRole('button',{name:'Aggiungi elemento',exact:true}).click();
  await page.getByLabel('Immagine dell’elemento · PNG/WebP').setInputFiles('public/icons/icon-192.png');await expect(page.locator('.studio-art img')).toBeVisible();await audit(page);await shot(page,'1440-element-image');
  await tab(page,'Ricette');await page.getByLabel('Ingrediente A',{exact:true}).selectOption('void');await page.getByLabel('Ingrediente B',{exact:true}).selectOption('void');await page.getByLabel('Risultato della ricetta',{exact:true}).selectOption('studio_browser_gemma_di_prova');await page.getByRole('button',{name:'Aggiungi requisito',exact:true}).click();await page.getByRole('button',{name:'Aggiungi ricetta',exact:true}).click();await audit(page);await shot(page,'1440-recipe-requirements');
  await tab(page,'Collezioni');await page.getByLabel('Nome Collezione',{exact:true}).fill('Taccuino personale');await page.getByLabel('Descrizione Collezione').fill('Una Collezione sintetica nello Studio.');await page.getByRole('checkbox',{name:'Gemma di prova',exact:true}).check();await page.getByRole('button',{name:'Aggiungi Collezione',exact:true}).click();
  await page.getByRole('button',{name:'Valida e simula bozza',exact:true}).click();await expect(page.getByText('68/68 raggiungibili',{exact:true})).toBeVisible();await audit(page);await shot(page,'1440-preview');
  await page.getByLabel('Percorso verso un elemento',{exact:true}).selectOption('studio_browser_gemma_di_prova');await expect(page.locator('.author-path')).toContainText('void + void');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Esporta ZIP della bozza',exact:true}).click();const artifact=await download;const exported=await readPack(new Uint8Array(readFileSync((await artifact.path())!)));expect(exported.patch.elements).toHaveLength(1);expect(exported.patch.recipes).toHaveLength(1);expect(exported.patch.collections).toHaveLength(1);expect(Object.keys(exported.assets)).toHaveLength(1);
  await page.getByRole('button',{name:'Installa bozza validata e riavvia',exact:true}).click();await expect(page.getByLabel('Attiva modalità autore locale')).not.toBeChecked();await page.goto('/');await expect(page.getByText('4 scoperte · 0 XP',{exact:true}).first()).toBeVisible();const select=page.getByRole('button',{name:/^Vuoto, elemento del set/});await select.click();await select.click();await page.getByRole('button',{name:'Combina',exact:true}).click();await expect(page.getByRole('heading',{name:'Gemma di prova',exact:true})).toBeVisible();await expect(page.locator('img[data-art-key="studio_browser.elements.studio_browser_gemma_di_prova"]').first()).toBeVisible();
  await page.getByRole('button',{name:'Nuovo esperimento',exact:true}).click();await open(page);await page.getByRole('button',{name:'Prepara aggiornamento studio_browser',exact:true}).click();await expect(page.getByLabel('Versione del pacchetto',{exact:true})).toHaveValue('1.0.1');await tab(page,'Elementi');await page.getByRole('button',{name:'Modifica studio_browser_gemma_di_prova',exact:true}).click();await page.getByLabel('Nome elemento',{exact:true}).fill('Gemma aggiornata');await page.getByRole('button',{name:'Salva elemento',exact:true}).click();await page.getByRole('button',{name:'Valida e simula bozza',exact:true}).click();await expect(page.getByText('68/68 raggiungibili',{exact:true})).toBeVisible();
});
test('mobile Studio builds new Set/unlock and blocks canonical collision; draft survives reload without entering gameplay',async({page})=>{
  await page.setViewportSize({width:390,height:844});await open(page);await tab(page,'Set');await page.getByLabel('Nome Set',{exact:true}).fill('Set personale');await page.getByLabel('Descrizione Set').fill('Set locale di prova.');await page.getByRole('button',{name:'Aggiungi Set',exact:true}).click();
  await tab(page,'Elementi');await page.getByLabel('Nome elemento',{exact:true}).fill('Seme personale');await page.getByLabel('Descrizione elemento').fill('Elemento di prova del Set personale.');await page.getByLabel('Set dell’elemento',{exact:true}).selectOption('my_pack_set_personale');await page.getByLabel(/^Completamento/).selectOption('required');await page.getByRole('button',{name:'Aggiungi elemento',exact:true}).click();await audit(page);await shot(page,'390-element');
  await tab(page,'Ricette');await page.getByLabel('Ingrediente A',{exact:true}).selectOption('energy');await page.getByLabel('Ingrediente B',{exact:true}).selectOption('energy');await page.getByLabel('Risultato della ricetta',{exact:true}).selectOption('my_pack_seme_personale');await expect(page.getByText(/Coppia già definita:/)).toBeVisible();await page.getByRole('button',{name:'Aggiungi ricetta',exact:true}).click();await page.getByRole('button',{name:'Valida e simula bozza',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Override PairKey seed');await expect(page.getByRole('button',{name:'Installa bozza validata e riavvia'})).toHaveCount(0);await shot(page,'390-conflict');
  await tab(page,'Ricette');await page.getByRole('button',{name:/^Modifica my_pack_energy_energy/}).click();await page.getByLabel('Ingrediente A',{exact:true}).selectOption('void');await page.getByLabel('Ingrediente B',{exact:true}).selectOption('void');await page.getByRole('button',{name:'Salva ricetta',exact:true}).click();
  await tab(page,'Unlock');await page.getByLabel('Destinazione dello sblocco',{exact:true}).selectOption('my_pack_set_personale');await page.getByLabel(/^Tipo di requisito/).selectOption('element_discovered');await page.getByLabel('Oggetto del requisito',{exact:true}).selectOption('my_pack_seme_personale');await page.getByRole('button',{name:'Aggiungi requisito',exact:true}).click();await page.getByRole('button',{name:'Aggiungi Unlock',exact:true}).click();await page.getByRole('button',{name:'Valida e simula bozza',exact:true}).click();await expect(page.getByText('68/68 raggiungibili',{exact:true})).toBeVisible();await audit(page);await shot(page,'390-preview');
  await page.reload();await page.getByLabel('Attiva modalità autore locale').check();await page.getByRole('button',{name:'Apri Studio contenuti',exact:true}).click();await tab(page,'Elementi');await expect(page.getByRole('button',{name:'Modifica my_pack_seme_personale',exact:true})).toBeVisible();
  await page.setViewportSize({width:320,height:568});await audit(page);await shot(page,'320-draft');
  await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await audit(page);await shot(page,'320-text-200');await page.evaluate(()=>{document.documentElement.style.fontSize='';});
  await page.emulateMedia({reducedMotion:'reduce',forcedColors:'active'});await audit(page);await shot(page,'320-forced-colors');
});
test('Phase 8A sandbox ZIP opens in the visual Studio and receives an element-specific raster without changing recipes',async({page})=>{
  await page.setViewportSize({width:390,height:844});await open(page);await page.getByLabel('Apri ZIP nello Studio').setInputFiles('tests/fixtures/phase-8a-proposed.zip');await expect(page.getByLabel('Identificatore del pacchetto',{exact:true})).toHaveValue('phase_8a_proposed');await tab(page,'Elementi');await page.getByLabel('Cerca nella bozza').fill('fish');await page.getByRole('button',{name:'Modifica fish',exact:true}).click();await expect(page.getByLabel('Nome elemento',{exact:true})).toHaveValue('Pesce');await page.getByLabel('Immagine dell’elemento · PNG/WebP').setInputFiles('public/icons/icon-192.png');await expect(page.locator('.studio-art img')).toBeVisible();await audit(page);await shot(page,'390-phase-8a-artwork');
  await page.getByRole('button',{name:'Valida e simula bozza',exact:true}).click();await expect(page.getByText('118/118 raggiungibili',{exact:true})).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Esporta ZIP della bozza',exact:true}).click();const zip=await readPack(new Uint8Array(readFileSync((await(await download).path())!)));expect(zip.patch.recipes).toHaveLength(51);expect(zip.patch.elements!.find(e=>e.id==='fish')!.artKey).toBe('phase_8a.elements.fish');expect(zip.patch.elements!.find(e=>e.id==='shark')!.artKey).toBe('elements.aquatic');expect(zip.manifest.reviewStatus).toBe('proposed');
});
